<article>
    <h1>
	 	Demostrar que el determinante es cero empleando las propiedades de las matrices
    	<p><time datetime="{{NOW}}" pubdate="{{NOW}}">{{NOW}}</time></p>
	</h1>

	<h3>Debemos demostrar que el determinante es cero y solo podemos para ello usar las propiedades de las matrices</h3>

	$$
	\begin{vmatrix}
		a & b \\
		c & d
	\end{vmatrix}
	$$



	<p>
	    El universo son números y las matemáticas permiten estudiar, analizar y en ocasiones predecir lo que ocurrirá en el futuro.
	</p>
</article>
