<article data-section="matemáticas" data-keywords="números">
    <h1>
		Los números están en todas partes
    	<p><time datetime="{{NOW}}" pubdate="{{NOW}}">{{NOW}}</time></p>
	</h1>

	<ul>
    <li>El número de letras que contiene este artículo</li>
    <li>El número de personas que están viendo un vídeo en youtube</li>
    <li>El número de veces que una persona está quejandose a lo largo de un día</li>
    <li>El número de miradas que recibe alguien</li>
    <li>El número de veces que alguien se rasca la nariz</li>
    <li>El número de mensajes que tengo en Whatsapp</li>
    <li>...</li>
	</ul>

	<eq>x = \frac{27 \pm \sqrt{b^2-4ac}}{2a}</eq>


	<p>
	    El universo son números y las matemáticas permiten estudiar, analizar y en ocasiones predecir lo que ocurrirá en el futuro.
	</p>
</article>
